version: '2'
services:
  ui:
    build: ./client
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '4000:4000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
